# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails - a model defined in OpenAPI

        lat: The lat of this GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails.
        long: The long of this GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails.
        operator_id: The operator_id of this GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails.
        owner_id: The owner_id of this GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails.
        alt: The alt of this GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails [Optional].
    """

    lat: float = Field(alias="lat")
    long: float = Field(alias="long")
    operator_id: int = Field(alias="operatorId")
    owner_id: int = Field(alias="ownerId")
    alt: Optional[float] = Field(alias="alt", default=None)

GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails.update_forward_refs()
