# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetScenarioRanges200ResponseInnerIndexesCategoryInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerIndexesCategoryInner - a model defined in OpenAPI

        id: The id of this GetScenarioRanges200ResponseInnerIndexesCategoryInner.
        name: The name of this GetScenarioRanges200ResponseInnerIndexesCategoryInner.
        era: The era of this GetScenarioRanges200ResponseInnerIndexesCategoryInner.
        parent: The parent of this GetScenarioRanges200ResponseInnerIndexesCategoryInner [Optional].
        code: The code of this GetScenarioRanges200ResponseInnerIndexesCategoryInner [Optional].
    """

    id: int = Field(alias="id")
    name: str = Field(alias="name")
    era: str = Field(alias="era")
    parent: Optional[int] = Field(alias="parent", default=None)
    code: Optional[str] = Field(alias="code", default=None)

GetScenarioRanges200ResponseInnerIndexesCategoryInner.update_forward_refs()
