# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from api_python_server.models.get_scenario_ranges200_response_inner_time_range_step import GetScenarioRanges200ResponseInnerTimeRangeStep


class GetScenarioRanges200ResponseInnerTimeRange(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerTimeRange - a model defined in OpenAPI

        start: The start of this GetScenarioRanges200ResponseInnerTimeRange [Optional].
        end: The end of this GetScenarioRanges200ResponseInnerTimeRange [Optional].
        step: The step of this GetScenarioRanges200ResponseInnerTimeRange [Optional].
    """

    start: Optional[datetime] = Field(alias="start", default=None)
    end: Optional[datetime] = Field(alias="end", default=None)
    step: Optional[GetScenarioRanges200ResponseInnerTimeRangeStep] = Field(alias="step", default=None)

GetScenarioRanges200ResponseInnerTimeRange.update_forward_refs()
