# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from api_python_server.models.get_scenario_ranges200_response_inner_indexes_area_inner import GetScenarioRanges200ResponseInnerIndexesAreaInner
from api_python_server.models.get_scenario_ranges200_response_inner_indexes_category_inner import GetScenarioRanges200ResponseInnerIndexesCategoryInner
from api_python_server.models.get_scenario_ranges200_response_inner_indexes_entity_inner import GetScenarioRanges200ResponseInnerIndexesEntityInner


class GetScenarioRanges200ResponseInnerIndexes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerIndexes - a model defined in OpenAPI

        entity: The entity of this GetScenarioRanges200ResponseInnerIndexes [Optional].
        area: The area of this GetScenarioRanges200ResponseInnerIndexes [Optional].
        category: The category of this GetScenarioRanges200ResponseInnerIndexes [Optional].
    """

    entity: Optional[List[GetScenarioRanges200ResponseInnerIndexesEntityInner]] = Field(alias="entity", default=None)
    area: Optional[List[GetScenarioRanges200ResponseInnerIndexesAreaInner]] = Field(alias="area", default=None)
    category: Optional[List[GetScenarioRanges200ResponseInnerIndexesCategoryInner]] = Field(alias="category", default=None)

GetScenarioRanges200ResponseInnerIndexes.update_forward_refs()
