# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from api_python_server.models.get_scenario_ranges200_response_inner_indexes import GetScenarioRanges200ResponseInnerIndexes
from api_python_server.models.get_scenario_ranges200_response_inner_time_range import GetScenarioRanges200ResponseInnerTimeRange


class GetScenarioRanges200ResponseInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInner - a model defined in OpenAPI

        time_range: The time_range of this GetScenarioRanges200ResponseInner [Optional].
        indexes: The indexes of this GetScenarioRanges200ResponseInner [Optional].
        data: The data of this GetScenarioRanges200ResponseInner [Optional].
    """

    time_range: Optional[GetScenarioRanges200ResponseInnerTimeRange] = Field(alias="time_range", default=None)
    indexes: Optional[GetScenarioRanges200ResponseInnerIndexes] = Field(alias="indexes", default=None)
    data: Optional[List[List[float]]] = Field(alias="data", default=None)

GetScenarioRanges200ResponseInner.update_forward_refs()
