# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetScenarioRanges200ResponseInnerTimeRangeStep(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerTimeRangeStep - a model defined in OpenAPI

    """


GetScenarioRanges200ResponseInnerTimeRangeStep.update_forward_refs()
