# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from api_python_server.models.get_scenario_ranges200_response_inner_indexes_entity_inner_details import GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails


class GetScenarioRanges200ResponseInnerIndexesEntityInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerIndexesEntityInner - a model defined in OpenAPI

        id: The id of this GetScenarioRanges200ResponseInnerIndexesEntityInner [Optional].
        parent: The parent of this GetScenarioRanges200ResponseInnerIndexesEntityInner [Optional].
        name: The name of this GetScenarioRanges200ResponseInnerIndexesEntityInner [Optional].
        type: The type of this GetScenarioRanges200ResponseInnerIndexesEntityInner [Optional].
        image: The image of this GetScenarioRanges200ResponseInnerIndexesEntityInner [Optional].
        details: The details of this GetScenarioRanges200ResponseInnerIndexesEntityInner [Optional].
    """

    id: Optional[int] = Field(alias="id", default=None)
    parent: Optional[int] = Field(alias="parent", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    type: Optional[str] = Field(alias="type", default=None)
    image: Optional[AnyUrl] = Field(alias="image", default=None)
    details: Optional[GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails] = Field(alias="details", default=None)

GetScenarioRanges200ResponseInnerIndexesEntityInner.update_forward_refs()
