# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from api_python_server.models.get_scenario_ranges200_response_inner_indexes_area_inner_details import GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails


class GetScenarioRanges200ResponseInnerIndexesAreaInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerIndexesAreaInner - a model defined in OpenAPI

        id: The id of this GetScenarioRanges200ResponseInnerIndexesAreaInner.
        name: The name of this GetScenarioRanges200ResponseInnerIndexesAreaInner.
        type: The type of this GetScenarioRanges200ResponseInnerIndexesAreaInner.
        parent: The parent of this GetScenarioRanges200ResponseInnerIndexesAreaInner [Optional].
        details: The details of this GetScenarioRanges200ResponseInnerIndexesAreaInner [Optional].
    """

    id: int = Field(alias="id")
    name: str = Field(alias="name")
    type: str = Field(alias="type")
    parent: Optional[int] = Field(alias="parent", default=None)
    details: Optional[GetScenarioRanges200ResponseInnerIndexesAreaInnerDetails] = Field(alias="details", default=None)

GetScenarioRanges200ResponseInnerIndexesAreaInner.update_forward_refs()
