# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails - a model defined in OpenAPI

        supplier: The supplier of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        customer: The customer of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        own_operation: The own_operation of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        financial_control: The financial_control of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        operational_control: The operational_control of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        capital: The capital of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        registration: The registration of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
        address: The address of this GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails [Optional].
    """

    supplier: Optional[bool] = Field(alias="supplier", default=None)
    customer: Optional[bool] = Field(alias="customer", default=None)
    own_operation: Optional[bool] = Field(alias="ownOperation", default=None)
    financial_control: Optional[bool] = Field(alias="financialControl", default=None)
    operational_control: Optional[bool] = Field(alias="operationalControl", default=None)
    capital: Optional[bool] = Field(alias="capital", default=None)
    registration: Optional[str] = Field(alias="registration", default=None)
    address: Optional[str] = Field(alias="address", default=None)

GetScenarioRanges200ResponseInnerIndexesEntityInnerDetails.update_forward_refs()
