# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ListScenarios200ResponseInnerMetadata(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListScenarios200ResponseInnerMetadata - a model defined in OpenAPI

        time_range: The time_range of this ListScenarios200ResponseInnerMetadata [Optional].
        data_quality: The data_quality of this ListScenarios200ResponseInnerMetadata [Optional].
    """

    time_range: Optional[str] = Field(alias="timeRange", default=None)
    data_quality: Optional[str] = Field(alias="dataQuality", default=None)

ListScenarios200ResponseInnerMetadata.update_forward_refs()
