# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from api_python_server.models.list_scenarios200_response_inner_metadata import ListScenarios200ResponseInnerMetadata


class ListScenarios200ResponseInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListScenarios200ResponseInner - a model defined in OpenAPI

        id: The id of this ListScenarios200ResponseInner [Optional].
        title: The title of this ListScenarios200ResponseInner [Optional].
        parent_scenario_id: The parent_scenario_id of this ListScenarios200ResponseInner [Optional].
        metadata: The metadata of this ListScenarios200ResponseInner [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    title: Optional[str] = Field(alias="title", default=None)
    parent_scenario_id: Optional[str] = Field(alias="parentScenarioId", default=None)
    metadata: Optional[ListScenarios200ResponseInnerMetadata] = Field(alias="metadata", default=None)

ListScenarios200ResponseInner.update_forward_refs()
