# coding: utf-8

"""
    API B2B ADICT V2

    Cette API vous permet de gérer vos droits d'accès aux données des PCE et de consulter leurs données contractuelles, techniques, de consommation publiées / informatives et d'injections publiées.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""

import unittest

import grdf_client
from grdf_client.model.get_pce_id_pce_donnees_contractuelles500_response import GetPceIdPceDonneesContractuelles500Response
from grdf_client import configuration


class TestGetPceIdPceDonneesContractuelles500Response(unittest.TestCase):
    """GetPceIdPceDonneesContractuelles500Response unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
