# coding: utf-8

"""
    The Natixar ESG impact assessment open API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from api_python_server.apis.clients_api import router as ClientsApiRouter
from api_python_server.apis.health_api import router as HealthApiRouter
from api_python_server.apis.scenario_api import router as ScenarioApiRouter

app = FastAPI(
    title="The Natixar ESG impact assessment open API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.0.0",
    root_path="/core/v1",
)

app.include_router(ClientsApiRouter)
app.include_router(HealthApiRouter)
app.include_router(ScenarioApiRouter)
