# coding: utf-8

"""
    API B2B ADICT V2

    Cette API vous permet de gérer vos droits d'accès aux données des PCE et de consulter leurs données contractuelles, techniques, de consommation publiées / informatives et d'injections publiées.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from grdf_client import schemas  # noqa: F401


class BordereauPublication(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            date_debut_bordereau = schemas.DateSchema
            date_fin_bordereau = schemas.DateSchema
            nb_jour_gazier = schemas.NumberSchema
            __annotations__ = {
                "date_debut_bordereau": date_debut_bordereau,
                "date_fin_bordereau": date_fin_bordereau,
                "nb_jour_gazier": nb_jour_gazier,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_debut_bordereau"]) -> MetaOapg.properties.date_debut_bordereau: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_fin_bordereau"]) -> MetaOapg.properties.date_fin_bordereau: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nb_jour_gazier"]) -> MetaOapg.properties.nb_jour_gazier: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["date_debut_bordereau", "date_fin_bordereau", "nb_jour_gazier", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_debut_bordereau"]) -> typing.Union[MetaOapg.properties.date_debut_bordereau, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_fin_bordereau"]) -> typing.Union[MetaOapg.properties.date_fin_bordereau, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nb_jour_gazier"]) -> typing.Union[MetaOapg.properties.nb_jour_gazier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["date_debut_bordereau", "date_fin_bordereau", "nb_jour_gazier", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        date_debut_bordereau: typing.Union[MetaOapg.properties.date_debut_bordereau, str, date, schemas.Unset] = schemas.unset,
        date_fin_bordereau: typing.Union[MetaOapg.properties.date_fin_bordereau, str, date, schemas.Unset] = schemas.unset,
        nb_jour_gazier: typing.Union[MetaOapg.properties.nb_jour_gazier, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BordereauPublication':
        return super().__new__(
            cls,
            *args,
            date_debut_bordereau=date_debut_bordereau,
            date_fin_bordereau=date_fin_bordereau,
            nb_jour_gazier=nb_jour_gazier,
            _configuration=_configuration,
            **kwargs,
        )
