# coding: utf-8

"""
    API B2B ADICT V2

    Cette API vous permet de gérer vos droits d'accès aux données des PCE et de consulter leurs données contractuelles, techniques, de consommation publiées / informatives et d'injections publiées.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from grdf_client import schemas  # noqa: F401


class CoeffCalcul(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            coeff_pta = schemas.NumberSchema
            valeur_pcs = schemas.NumberSchema
            coeff_conversion = schemas.NumberSchema
            __annotations__ = {
                "coeff_pta": coeff_pta,
                "valeur_pcs": valeur_pcs,
                "coeff_conversion": coeff_conversion,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["coeff_pta"]) -> MetaOapg.properties.coeff_pta: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["valeur_pcs"]) -> MetaOapg.properties.valeur_pcs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["coeff_conversion"]) -> MetaOapg.properties.coeff_conversion: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["coeff_pta", "valeur_pcs", "coeff_conversion", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["coeff_pta"]) -> typing.Union[MetaOapg.properties.coeff_pta, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["valeur_pcs"]) -> typing.Union[MetaOapg.properties.valeur_pcs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["coeff_conversion"]) -> typing.Union[MetaOapg.properties.coeff_conversion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["coeff_pta", "valeur_pcs", "coeff_conversion", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        coeff_pta: typing.Union[MetaOapg.properties.coeff_pta, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        valeur_pcs: typing.Union[MetaOapg.properties.valeur_pcs, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        coeff_conversion: typing.Union[MetaOapg.properties.coeff_conversion, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CoeffCalcul':
        return super().__new__(
            cls,
            *args,
            coeff_pta=coeff_pta,
            valeur_pcs=valeur_pcs,
            coeff_conversion=coeff_conversion,
            _configuration=_configuration,
            **kwargs,
        )
