# coding: utf-8

"""
    API B2B ADICT V2

    Cette API vous permet de gérer vos droits d'accès aux données des PCE et de consulter leurs données contractuelles, techniques, de consommation publiées / informatives et d'injections publiées.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from grdf_client import schemas  # noqa: F401


class Retour200DonneesContractuelles(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def pce() -> typing.Type['PceIdentifiant']:
                return PceIdentifiant
        
            @staticmethod
            def donnees_contractuelles() -> typing.Type['DonneesContractuelles']:
                return DonneesContractuelles
            statut_restitution = schemas.DictSchema
            __annotations__ = {
                "pce": pce,
                "donnees_contractuelles": donnees_contractuelles,
                "statut_restitution": statut_restitution,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pce"]) -> 'PceIdentifiant': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["donnees_contractuelles"]) -> 'DonneesContractuelles': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statut_restitution"]) -> MetaOapg.properties.statut_restitution: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["pce", "donnees_contractuelles", "statut_restitution", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pce"]) -> typing.Union['PceIdentifiant', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["donnees_contractuelles"]) -> typing.Union['DonneesContractuelles', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statut_restitution"]) -> typing.Union[MetaOapg.properties.statut_restitution, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["pce", "donnees_contractuelles", "statut_restitution", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        pce: typing.Union['PceIdentifiant', schemas.Unset] = schemas.unset,
        donnees_contractuelles: typing.Union['DonneesContractuelles', schemas.Unset] = schemas.unset,
        statut_restitution: typing.Union[MetaOapg.properties.statut_restitution, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Retour200DonneesContractuelles':
        return super().__new__(
            cls,
            *args,
            pce=pce,
            donnees_contractuelles=donnees_contractuelles,
            statut_restitution=statut_restitution,
            _configuration=_configuration,
            **kwargs,
        )

from grdf_client.model.donnees_contractuelles import DonneesContractuelles
from grdf_client.model.pce_identifiant import PceIdentifiant
