# coding: utf-8

"""
    API B2B ADICT V2

    Cette API vous permet de gérer vos droits d'accès aux données des PCE et de consulter leurs données contractuelles, techniques, de consommation publiées / informatives et d'injections publiées.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""

from grdf_client.paths.droits_acces.get import ConsulterAcces
from grdf_client.paths.pce_id_pce_droit_acces.put import DroitAcces
from grdf_client.paths.droit_acces_id_droit_acces.patch import FinAcces
from grdf_client.paths.droits_acces.post import POstDroitsAcces
from grdf_client.paths.droit_acces_id_droit_acces_preuves.put import Preuve


class DroitsDaccsApi(
    ConsulterAcces,
    DroitAcces,
    FinAcces,
    POstDroitsAcces,
    Preuve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
