# coding: utf-8

# flake8: noqa

"""
    API B2B ADICT V2

    Cette API vous permet de gérer vos droits d'accès aux données des PCE et de consulter leurs données contractuelles, techniques, de consommation publiées / informatives et d'injections publiées.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from grdf_client.api_client import ApiClient

# import Configuration
from grdf_client.configuration import Configuration

# import exceptions
from grdf_client.exceptions import OpenApiException
from grdf_client.exceptions import ApiAttributeError
from grdf_client.exceptions import ApiTypeError
from grdf_client.exceptions import ApiValueError
from grdf_client.exceptions import ApiKeyError
from grdf_client.exceptions import ApiException
